development: &base
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: vantage_api

test:
  <<: *base
  database: vantage_api_test

production:
  <<: *base
  database: vantage_api
